### ISSUE TITLE
User can add a to-do

### ISSUE THREAD

**Issue by ChrisJVoss** [ChrisJVoss/call-bot#1]
# Motivation
Users will want to store their to-dos

# Implementation
- [x] Create a wireframe.
- [x] Create index.html, styles.css, main.js and link them.
- [x] Link Materialize.
- [x] Create header and sub-header.
- [x] Create to-do entry form.
- [x] Store to-do objects.
- [x] Create a database.
- [x] Use KNEX to add tasks to the database.
- [x] Set up an Express app to route POST requests to KNEX

![screen shot 2017-07-12 at 4 17 50 pm](https://user-images.githubusercontent.com/29046393/28144083-5a4a1fbe-671e-11e7-94cb-f7eae532c765.png)
