### ISSUE TITLE
User can hear an automated message of their to-do

### ISSUE THREAD

**Issue by ChrisJVoss** [ChrisJVoss/call-bot#3]
# Motivation
Users will want to hear what their tasks are.

# Implementation
- [x]  Using knex, sort database table by date and time.
- [x]  Use the POST method to register a route that responds by sending a .xml file.
- [x] Hide important information with .gitignore.
- [x] Write a functions that takes the 'task' portion of a to-do and wraps it in twiML.
- [x] Using knex, write a function that queries the database for the next upcoming to-do.
- [x] Write a function that compares current time with stored times and then executes the phone call code when the times synchronize.
